name:                hs-bench-build
version:             0.1.0.0
github:              "dgaw/hs-bench-build"
license:             BSD3
author:              "Damian Gaweda"
maintainer:          "damian.gaweda@gmail.com"
copyright:           "2018 Damian Gaweda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dgaw/hs-bench-build#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- bytestring >= 0.10.8.2
- unix
- time

library:
  source-dirs: src

executables:
  hs-bench-build:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hs-bench-build

tests:
  hs-bench-build-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hs-bench-build
